
const Westernwear = [

	{
		Name: "Abhisarika Superior Dress",
		Category: "Top_wear",
		Fabric: "Rayon",
		Price: "452",
		MRP: "502",
		Discount: "10% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "4.3",
		image: "https://images.meesho.com/images/products/68727547/0gljd_512.jpg",
		Size: "M, L, XL, XXL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: "Alia Elastic Maxi Anarkali dress",
		Category: "Top_wear",
		Fabric: "Rayon",
		Price: "284",
		MRP: "333",
		Discount: "15% off",
		offer: "₹49 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "4.2",
		image: "https://images.meesho.com/images/products/93232738/9t8gr_512.jpg",
		Size: "S, M, L, XL, XXL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: "Charming Maroon Off-Shoulder Pleated Fit & Flare Dress",
		Category: "Top_wear",
		Fabric: "Polyester",
		Price: "401",
		MRP: "451",
		Discount: "11% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "4.1",
		image: "https://images.meesho.com/images/products/85017447/yjutl_512.jpg",
		Size: "XS, M, L",
		Pattern: "Solid",
		Country_of_Origin: "India"
	},
	{
		Name: "comfy elegent dresses",
		Category: "Top_wear",
		Fabric: "Poly Crepe",
		Price: "158",
		MRP: "185",
		Discount: "15% off",
		offer: "₹27 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "4.5",
		image: "https://images.meesho.com/images/products/78588888/9r9vj_512.jpg",
		Size: "S, XL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: "Alisha Attractive Dresses",
		Category: "Top_wear",
		Fabric: "",
		Price: "439",
		MRP: "489",
		Discount: "10% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Delivery ₹72",
		Rating: "3.8",
		image: "https://images.meesho.com/images/products/82229492/ihdyi_512.jpg",
		Size: "M, L, XL, XXL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: "Womans Dresses",
		Category: "Top_wear",
		Fabric: "Cotton",
		Price: "628",
		MRP: "670",
		Discount: "7% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "",
		image: "https://images.meesho.com/images/products/88562224/dosaw_512.jpg",
		Size: "XS, S, M, L, XL, XXL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: "Trendy Graceful Women Dresses",
		Category: "Top_wear",
		Fabric: "Cotton",
		Price: "251",
		MRP: "295",
		Discount: "15% off",
		offer: "₹44 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.0",
		image: "https://images.meesho.com/images/products/64560486/juzkq_512.jpg",
		Size: "S, M, L, XL, XXL",
		Pattern: "Solid",
		Country_of_Origin: "India"
	},
	{
		Name: "IDRISHI COLLECTION DRESS",
		Category: "Top_wear",
		Fabric: "Crepe",
		Price: "290",
		MRP: "340",
		Discount: "15% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.6",
		image: "https://images.meesho.com/images/products/74491443/kusrw_512.jpg",
		Size: "XS, S, M, L, XL, XXL, XXXL, 4XL, 5XL, 6XL, 7XL",
		Pattern: "Solid",
		Country_of_Origin: "India"
	},
	{
		Name: "Classy Fashionista Women Dresses",
		Category: "Top_wear",
		Fabric: "Poly Crepe",
		Price: "240",
		MRP: "282",
		Discount: "15% off",
		offer: "₹42 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.9",
		image: "https://images.meesho.com/images/products/12673121/9229a_512.jpg",
		Size: "XS, S, M, L, XL",
		Pattern: "Solid",
		Country_of_Origin: "India"
	},
	{
		Name: "Dresses",
		Category: "Top_wear",
		Fabric: "Crepe",
		Price: "184",
		MRP: "216",
		Discount: "15% off",
		offer: "₹32 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.3",
		image: "https://images.meesho.com/images/products/58678798/an4ct_512.jpg",
		Size: "M, L, XL, XXL",
		Pattern: "Printed",
		Country_of_Origin: "India"
	},
	{
		Name: " Broadstar Women's High Waist Slim Fit Regular Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "672",
		MRP: "722",
		Discount: "7% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "2.8",
		image: "https://images.meesho.com/images/products/29518144/ea416_512.jpg",
		Size: "28, 30, 32, 34, 36, 38",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Broadstar Women's High Waist Slim Fit Regular Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "819",
		MRP: "869",
		Discount: "6% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "4.2",
		image: "https://images.meesho.com/images/products/93232738/9t8gr_512.jpg",
		Size: "28, 30, 32, 34, 36, 38",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: " Broadstar Women's High Waist Slim Fit Regular Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "672",
		MRP: "722",
		Discount: "7% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "",
		image: "https://images.meesho.com/images/products/29518172/7d3fe_512.jpg",
		Size: "28, 30, 34, 36, 38",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Coloured Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "759",
		MRP: "809",
		Discount: "6% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "",
		image: "https://images.meesho.com/images/products/96904524/4wjom_512.jpg",
		Size: "24, 26, 28, 30, 32",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Stylish Women's Denim Jeans",
		Category: "Bottom_wear",
		Fabric: "",
		Price: "528",
		MRP: "570",
		Discount: "9% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Delivery ₹72",
		Rating: "4.0",
		image: "https://images.meesho.com/images/products/2350016/1_512.jpg",
		Size: "26, 28, 30, 32, 34, 36, 38",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Women's Fitted Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "190",
		MRP: "223",
		Discount: "15% off",
		offer: "₹33 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.4",
		image: "https://images.meesho.com/images/products/58810515/dlhyz_512.jpg",
		Size: "26, 28, 30",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Casual Latest Women Jens Surface Styling : Fringed",
		Category: "Bottom_wear",
		Fabric: "",
		Price: "218",
		MRP: "257",
		Discount: "15% off",
		offer: "₹38 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.9",
		image: "https://images.meesho.com/images/products/47859893/esg1h_512.jpg",
		Size: "26, 28, 30",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Classy Fashionista Women Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "249",
		MRP: "309",
		Discount: "15% off",
		offer: "₹42 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.6",
		image: "https://images.meesho.com/images/products/40669780/tignf_512.jpg",
		Size: "24, 26, 28, 30, 32, 34",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "Classic Partywear Women Jeans",
		Category: "Bottom_wear",
		Fabric: "Denim",
		Price: "212",
		MRP: "249",
		Discount: "15% off",
		offer: "₹37 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.5",
		image: "https://images.meesho.com/images/products/46613681/13jpj_512.jpg",
		Size: "26, 28, 30",
		Pattern: "",
		Country_of_Origin: "India"
	},
	{
		Name: "RAVISHING WOMEN PLAIN 5-BUTTON JEANS",
		Category: "Bottom_wear",
		Fabric: "Cotton Blend",
		Price: "348",
		MRP: "390",
		Discount: "13% off",
		offer: "₹50 discount on 1st order",
		Delivery_Type: "Free Delivery",
		Rating: "3.6",
		image: "https://images.meesho.com/images/products/89967254/nops6_512.jpg",
		Size: "28, 30, 32",
		Pattern: "",
		Country_of_Origin: "India"
	},
]

export default Westernwear



